# Generated by Django 3.1.7 on 2021-04-17 17:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest_ID', models.CharField(max_length=20)),
                ('chest_name', models.CharField(blank=True, max_length=255)),
                ('chest_dir', models.CharField(max_length=400)),
                ('chest_size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=100)),
                ('chest', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='kycweb.chest')),
            ],
        ),
        migrations.CreateModel(
            name='FileInstances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_path', models.CharField(blank=True, max_length=400)),
                ('file_type', models.CharField(blank=True, max_length=400)),
                ('chest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='File', to='kycweb.chest')),
            ],
        ),
        migrations.CreateModel(
            name='WorkChestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract_chest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_chest_info', to='kycweb.chest')),
                ('cogc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cogc', to='kycweb.fileinstances')),
                ('kra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_kra', to='kycweb.fileinstances')),
                ('nhif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhif', to='kycweb.fileinstances')),
                ('nssf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nssf', to='kycweb.fileinstances')),
                ('wrk_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_id', to='kycweb.fileinstances')),
            ],
        ),
        migrations.CreateModel(
            name='Usr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='static/default_pfp.jpg', upload_to='profile_pics')),
                ('phone_number', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0799999999'.", regex='^07[0-9]{8}')])),
                ('ctx_id', models.CharField(blank=True, max_length=14)),
                ('data_dir', models.CharField(blank=True, max_length=400)),
                ('def_usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cust_usr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HitsRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tstmp', models.DateTimeField(auto_now_add=True)),
                ('chest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kycweb.chest')),
                ('corporation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kycweb.corporation')),
                ('usr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kycweb.usr')),
            ],
        ),
        migrations.CreateModel(
            name='ChestRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.BooleanField(default=True, verbose_name='user access')),
                ('chest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kycweb.chest')),
                ('corporation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kycweb.corporation')),
                ('usr', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kycweb.usr')),
            ],
        ),
        migrations.AddField(
            model_name='chest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chest', to='kycweb.usr'),
        ),
        migrations.CreateModel(
            name='BankingChestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract_chest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bnk_chest_info', to='kycweb.chest')),
                ('bnk_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bnk_id', to='kycweb.fileinstances')),
                ('kra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kra', to='kycweb.fileinstances')),
                ('utility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility', to='kycweb.fileinstances')),
            ],
        ),
        migrations.CreateModel(
            name='AuthLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='none', max_length=256)),
                ('enabled', models.BooleanField(verbose_name='external auth enabled')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='kycweb.usr')),
            ],
        ),
    ]
