# Generated by Django 3.1.7 on 2021-04-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr',
            name='bdate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usr',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
