# Generated by Django 3.1.7 on 2021-04-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0002_auto_20210417_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr',
            name='addr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usr',
            name='bdate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
