# Generated by Django 3.1.7 on 2021-04-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0004_auto_20210421_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('validator', models.CharField(blank=True, max_length=256, null=True)),
                ('pattern', models.CharField(blank=True, max_length=256, null=True)),
                ('identifier', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fileinstances',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='fileinstances',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='fileinstances',
            name='validator',
        ),
        migrations.AlterField(
            model_name='fileinstances',
            name='file_type',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='fileinstances',
            name='upload_path',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
