# Generated by Django 3.1.7 on 2021-04-23 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0007_auto_20210423_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlevel',
            name='chest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_information_source', to='kycweb.chest'),
            preserve_default=False,
        ),
    ]
