# Generated by Django 3.1.7 on 2021-04-29 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0010_auto_20210429_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chestregistry',
            name='access',
            field=models.BooleanField(default=False, verbose_name='user access'),
        ),
        migrations.AlterField(
            model_name='chestregistry',
            name='corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kycweb.corporation'),
        ),
        migrations.AlterField(
            model_name='chestregistry',
            name='usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kycweb.usr'),
        ),
    ]
