# Generated by Django 3.1.7 on 2021-04-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0011_auto_20210429_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlevel',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='external auth enabled'),
        ),
    ]
