# Generated by Django 3.1.7 on 2021-04-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0012_auto_20210430_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='chest',
            name='application',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
