# Generated by Django 3.1.7 on 2021-04-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0013_chest_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='authlevel',
            name='max',
            field=models.BooleanField(default=False, verbose_name='Max_auth_for_application'),
        ),
    ]
