# Generated by Django 3.1.7 on 2021-05-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0014_authlevel_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='key',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
