# Generated by Django 3.1.7 on 2021-05-03 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0016_auto_20210501_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitsregistry',
            name='corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kycweb.corporation'),
        ),
    ]
