# Generated by Django 3.1.7 on 2021-05-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0018_corpkeyuses_hostregistry'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='company_key_enabled'),
        ),
    ]
