# Generated by Django 3.1.7 on 2021-05-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0019_corporation_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpkeyuses',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
