# Generated by Django 3.1.7 on 2021-05-14 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0020_corpkeyuses_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=10, null=True)),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('bdate', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, max_length=7, null=True)),
                ('district_ob', models.CharField(blank=True, max_length=25, null=True)),
                ('place_oi', models.CharField(blank=True, max_length=25, null=True)),
                ('issue_date', models.CharField(blank=True, max_length=8, null=True)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nat_id', to='kycweb.usr')),
            ],
        ),
        migrations.CreateModel(
            name='KRAPinCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(blank=True, max_length=12, null=True)),
                ('taxpayer_name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('addr', models.CharField(blank=True, max_length=500, null=True)),
                ('po_box', models.CharField(blank=True, max_length=30, null=True)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kra_pin', to='kycweb.usr')),
            ],
        ),
    ]
