# Generated by Django 3.1.7 on 2021-05-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0021_krapincert_natid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natid',
            name='issue_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
