# Generated by Django 3.1.7 on 2021-05-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0024_auto_20210516_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='identifier',
            field=models.CharField(default='none', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
