# Generated by Django 3.1.7 on 2021-05-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0025_auto_20210517_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
