# Generated by Django 3.1.7 on 2021-05-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0026_auto_20210517_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticator',
            name='created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
