# Generated by Django 3.1.7 on 2021-05-17 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0027_authenticator_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticator',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corp_creator', to='kycweb.corporation'),
        ),
    ]
