# Generated by Django 3.1.7 on 2021-05-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0028_auto_20210517_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validator',
            old_name='auth',
            new_name='internal',
        ),
    ]
