# Generated by Django 3.1.7 on 2021-05-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycweb', '0030_auto_20210518_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='valinstance',
            name='ident',
            field=models.CharField(default='0', max_length=256, verbose_name='identifier'),
        ),
    ]
